version: '3.8'

services:
  capital-gains-app:
    image: openjdk:21
    container_name: capital-gains-app
    working_dir: /app
    volumes:
      - .:/app

  capital-gains-maven:
    image: maven:3.9
    container_name: capital-gains-maven
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
